OPDB/Models/HomeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace OPDB.Models
{
    public class HomeViewModel
    {
       public List<UserInfoViewModel> Information { get; set; }


    }
}

OPDB/Controllers/ActividadesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OPDB.Models;
using System.Globalization;
using System.Text.RegularExpressions;
using System.Data.Entity.Infrastructure;
using System.Data.Entity.Validation;

namespace OPDB.Controllers
{
    public class ActividadesController : Controller
    {
        private OPDBEntities db = new OPDBEntities();

        //
        // GET: /Actividades/

        public ActionResult Index(string requested)
        {
            if (requested != null)
            {
                if (User.Identity.IsAuthenticated && Boolean.Parse(requested))
                {

                    if (Int32.Parse(User.Identity.Name.ToString().Split(',')[1]) == 1)
                    {

                        List<Activity> activities = (from activity in db.Activities where activity.DeletionDate == null select activity).ToList();

                        ActivityViewModel activityViewModel = new ActivityViewModel
                        {
                            Information = new List<UserInfoViewModel>()
                        };

                        foreach (var activity in activities)
                        {
                            var CreateUser = db.Users.Find(activity.CreateUser);
                            var UpdateUser = db.Users.Find(activity.UpdateUser);

                            if (CreateUser.UserTypeID == 3 && UpdateUser.UserTypeID == 3)
                            {

                                activityViewModel.Information.Add(new UserInfoViewModel
                                 {
                                     Activity = activity,
                                     CreateEntity = db.OutreachEntityDetails.First(u => u.UserID == activity.CreateUser),
                                     UpdateEntity = db.OutreachEntityDetails.First(u => u.UserID == activity.UpdateUser),
                                     CreateUser = new UserDetail
                                     {
                                         FirstName = "",
                                         MiddleInitial = "",
                                         LastName = "",
                                     },
                                     UpdateUser = new UserDetail
                                     {
                                         FirstName = "",
                                         MiddleInitial = "",
                                         LastName = ""
                                     }

                                 });
                            }
                            else if (CreateUser.UserTypeID == 3 && UpdateUser.UserTypeID != 3)
                            {
                                activityViewModel.Information.Add(new UserInfoViewModel
                                {
                                    Activity = activity,
                                    CreateEntity = db.OutreachEntityDetails.First(u => u.UserID == activity.CreateUser),
                                    UpdateUser = db.UserDetails.First(u => u.UserID == activity.UpdateUser),
                                    CreateUser = new UserDetail
                                    {
                                        FirstName = "",
                                        MiddleInitial = "",
                                        LastName = "",

                                    },
                                    UpdateEntity = new OutreachEntityDetail
                                    {
                                        OutreachEntityName = ""
                                    }

                                });
                            }
                            else if (CreateUser.UserTypeID != 3 && UpdateUser.UserTypeID == 3)
                            {
                                activityViewModel.Information.Add(new UserInfoViewModel
                                {
                                    Activity = activity,
                                    CreateUser = db.UserDetails.First(u => u.UserID == activity.CreateUser),
                                    UpdateEntity = db.OutreachEntityDetails.First(u => u.UserID == activity.UpdateUser),
                                    UpdateUser = new UserDetail
                                    {
                                        FirstName = "",
                                        MiddleInitial = "",
                                        LastName = ""
                                    },
                                    CreateEntity = new OutreachEntityDetail
                                    {
                                        OutreachEntityName = ""
                                    }

                                });
                            }
                            else
                            {
                                activityViewModel.Information.Add(new UserInfoViewModel
                                {
                                    Activity = activity,
                                    CreateUser = db.UserDetails.First(u => u.UserID == activity.CreateUser),
                                    UpdateUser = db.UserDetails.First(u => u.UserID == activity.UpdateUser),
                                    CreateEntity = new OutreachEntityDetail
                                    {
                                        OutreachEntityName = ""
                                    },
                                    UpdateEntity = new OutreachEntityDetail
                                    {
                                        OutreachEntityName = ""
                                    }

                                });
                            }

                        }

                        return PartialView("Index", activityViewModel);
                    }
                    else
                    {
                        return RedirectToAction("AccesoDenegado", "Home");
                    }
                }
            }

            return RedirectToAction("AccesoDenegado", "Home");
        }

        public ActionResult Lista()
        {
            var activities = (from activity in db.Activities where activity.DeletionDate == null orderby activity.CreateDate descending select activity).ToList();

            User currentUser = null;

            if (User.Identity.IsAuthenticated)
            {
                int currentUserID = Int32.Parse(User.Identity.Name.Split(',')[0]);
                currentUser = db.Users.Find(currentUserID);
            }

            ActivityViewModel activityViewModel = new ActivityViewModel
            {
                Information = new List<UserInfoViewModel>()
            };

            foreach (var activity in activities)
            {
                var activityDynamic = new ActivityDynamic
                {
                    ActivityDynamic1 = ""
                };

                if (activity.ActivityDynamicID != null)
                    activityDynamic = db.ActivityDynamics.Find(activity.ActivityDynamicID);

                if (activity.ActivityDate == null)
                    activity.ActivityDate = new DateTime();

                if (activity.ActivityTime == null)
                    activity.ActivityTime = "";


                DateTime endDate = new DateTime();

                if (activity.ActivityDate != new DateTime() && activity.ActivityTime != "" && activity.Duration != null)
                    endDate = calculateDuration((DateTime) activity.ActivityDate, activity.ActivityTime, activity.Duration);

                List<OPDB.Models.Interest> interest = new List<OPDB.Models.Interest>();

                if (currentUser != null)
                {
                    interest = (from i in db.Interests where i.UserID == currentUser.UserID && i.ActivityID == activity.ActivityID select i).ToList();
                }

                bool interested = false;

                if (interest.Count == 1)
                    interested = true;

                activityViewModel.Information.Add(new UserInfoViewModel
                {
                    Activity = activity,
                    OutreachEntity = db.OutreachEntityDetails.First(outreach => outreach.UserID == activity.UserID),
                    Interested = interested,
                    ActivityDynamic = activityDynamic,
                    EndDate = endDate
                });
            }

            return View(activityViewModel);
        }

        public ActionResult DeInteres()
        {
            int currentUserID = Int32.Parse(User.Identity.Name.Split(',')[0]);

            var interested = (from interest in db.Interests join activity in db.Activities on interest.ActivityID equals activity.ActivityID where interest.DeletionDate == null && activity.DeletionDate == null && interest.UserID == currentUserID orderby activity.UpdateDate descending select interest).ToList();
           
            ActivityViewModel activityViewModel = new ActivityViewModel
            {
                Information = new List<UserInfoViewModel>()
            };

            foreach (var interest in interested)
            {
                var activity = db.Activities.Find(interest.ActivityID);

              if(activity.ActivityDynamic == null)
              {
                  activity.ActivityDynamic = new ActivityDynamic
                  {
                      ActivityDynamic1 = ""
                  };
             }

              if (activity.ActivityDate == null)
              {
                  activity.ActivityDate = new DateTime();
              }

              DateTime endDate = new DateTime();

              if (activity.ActivityDate != new DateTime() && activity.ActivityTime != "" && activity.Duration != null)

OPDB/Controllers/UnidadesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OPDB.Models;

namespace OPDB.Controllers
{
    public class UnidadesController : Controller
    {
        private OPDBEntities db = new OPDBEntities();

        //
        // GET: /Unidades/

        public ActionResult Index(string requested)
        {
            if (requested != null)
            {
                if (User.Identity.IsAuthenticated)
                {
                    if (Int32.Parse((User.Identity.Name.Split(',')[1])) == 1 && Boolean.Parse(requested))
                    {
                        List<Unit> units = (from unit in db.Units where unit.DeletionDate == null select unit).ToList();

                        UnitViewModel unitViewModel = new UnitViewModel
                        {
                            Information = new List<UserInfoViewModel>()
                        };


                        foreach (var unit in units)
                        {
                            unitViewModel.Information.Add(new UserInfoViewModel
                            {
                                Unit = unit,
                                CreateUser = db.UserDetails.First(u => u.UserID == unit.CreateUser),
                                UpdateUser = db.UserDetails.First(u => u.UserID == unit.UpdateUser)

                            });
                        }

                        return PartialView("Index", unitViewModel);
                    }
                }
            }
             
            return RedirectToAction("AccesoDenegado", "Home");
        }

        [HttpPost]
        public ActionResult Detalles(int id = 0)
        {
            if (User.Identity.IsAuthenticated)
            {
                if (Int32.Parse((User.Identity.Name.Split(',')[1])) == 1)
                {
                    UnitViewModel unitViewModel = new UnitViewModel
                    {
                        Unit = db.Units.Find(id)
                    };

                    if (unitViewModel.Unit == null)
                    {
                        return HttpNotFound();
                    }

                    return PartialView("Detalles", unitViewModel);
                }
            }

            return RedirectToAction("AccesoDenegado", "Home");
        }

        //
        // GET: /Unidades/Create

        [HttpPost]
        public ActionResult PopUpCrear()
        {
            if (User.Identity.IsAuthenticated)
            {
                if (Int32.Parse((User.Identity.Name.Split(',')[1])) == 1)
                {
                    return PartialView("Crear");
                }
            }

            return RedirectToAction("AccesoDenegado", "Home");
        }

        //
        // POST: /Unidades/Create

        [HttpPost]
        public ActionResult Crear(UnitViewModel unitViewModel)
        {
              if (ModelState.IsValid)
                {

                    if (Request.IsAuthenticated)
                    {
                        if (Int32.Parse((User.Identity.Name.Split(',')[1])) == 1)
                        {
                            unitViewModel.Unit.CreateDate = DateTime.Now;
                            unitViewModel.Unit.UpdateDate = DateTime.Now;

                            unitViewModel.Unit.CreateUser = Int32.Parse(User.Identity.Name.Split(',')[0]);
                            unitViewModel.Unit.UpdateUser = Int32.Parse(User.Identity.Name.Split(',')[0]);

                            db.Units.Add(unitViewModel.Unit);
                            db.SaveChanges();

                            return View("_Hack");
                        }
                    }
                    
                }

                return Content(GetErrorsFromModelState(unitViewModel));
            

        }

        [HttpPost]
        public ActionResult PopUpEditar(int id = 0)
        {
            if (User.Identity.IsAuthenticated)
            {
                if (Int32.Parse((User.Identity.Name.Split(',')[1])) == 1)
                {
                    UnitViewModel unitViewModel = new UnitViewModel
                    {
                        Unit = db.Units.Find(id)
                    };

                    if (unitViewModel.Unit == null)
                    {
                        return HttpNotFound();
                    }

                    return PartialView("Editar", unitViewModel);
                }
            }

            return RedirectToAction("AccesoDenegado", "Home");
        }

        //
        // POST: /Unidades/Edit/5

        [HttpPost]
        public ActionResult Editar(UnitViewModel unitViewModel)
        {
            if (User.Identity.IsAuthenticated)
            {
                if (Int32.Parse((User.Identity.Name.Split(',')[1])) == 1)
                {
                    if (ModelState.IsValid)
                    {
                        unitViewModel.Unit.UpdateUser = Int32.Parse(User.Identity.Name.Split(',')[0]);

                        unitViewModel.Unit.UpdateDate = DateTime.Now;
                        db.Entry(unitViewModel.Unit).State = EntityState.Modified;
                        db.SaveChanges();

                        return View("_Hack");
                    }

                    return Content(GetErrorsFromModelState(unitViewModel));
                }
            }

            return RedirectToAction("AccesoDenegado", "Home");
        }

        //
        // GET: /Unidades/Delete/5

        public ActionResult Remover(int id = 0)
        {
            if (User.Identity.IsAuthenticated)
            {
                if (Int32.Parse((User.Identity.Name.Split(',')[1])) == 1)
                {
                    Unit unit = db.Units.Find(id);

                    if (unit == null)
                    {
                        return HttpNotFound();
                    }
                    else
                    {
                        unit.DeletionDate = DateTime.Now;
                        db.Entry(unit).State = EntityState.Modified;
                        db.SaveChanges();
                    }

                    return RedirectToAction("Administracion", "Home");
                }
            }

            return RedirectToAction("AccesoDenegado", "Home");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }


        public String GetErrorsFromModelState(UnitViewModel unitViewModel)
        {

            //retrieves the validation messages from the ModelState as strings    
            var str = "";
            var errorSates = from state in ModelState.Values
                             from error in state.Errors
                             select error.ErrorMessage;

            var errorList = errorSates.ToList();
            foreach (var m in errorList)
            {
                str = str + "<li>* " + m + "</li>";
            }

            return str;
        }

        public ActionResult Lista()
        {
            var units = from unit in db.Units where unit.DeletionDate == null orderby unit.UnitName ascending select unit;

            return View(units.ToList());
        }
    }
}

OPDB/Views/Home/AccesoDenegado.cshtml
@{
    ViewBag.Title = "Acceso Denegado";
}

<center>
    <div class="large-12 columns panel">
        <img src="@Url.Content("~/Images/warning.ico")" /><br />
        <h1><b>Acceso Inválido</b></h1><br />
        <h3>Ha intentado accesar una acción del sistema para la cual no tiene permiso.</h3>
        <h3>Si necesita acceso, hable con algún administrador del sistema.</h3><br />
        <a href="@Url.Action("Index", "Home")" class="btn">Regresar</a>
    </div>
</center>

OPDB/Views/Home/Administracion.cshtml
@{
    ViewBag.Title = "Administracion";
}
    <nav class="top-bar" data-topbar role="navigation" id="adminBar">
        <section class="top-bar-section">
            <ul>
                <li id="outreachAdmin"><a id="outreachURL" onclick="loadAdminView(this)" data-url="@Url.Action("MenuAlcance", "Alcance", new { requested = true })">Alcance</a></li>
                <li id="activitiesAdmin"><a id="activitiesURL" onclick="loadAdminView(this)" data-url="@Url.Action("Index", "Actividades", new { requested = true })">Actividades</a></li>
                <li id="schoolsAdmin"><a id="schoolsURL" onclick="loadAdminView(this)" data-url="@Url.Action("MenuEscuelas", "Escuelas", new { requested = true })">Escuelas</a></li>
                <li id="resourcesAdmin"><a id="resourcesURL" onclick="loadAdminView(this)" data-url="@Url.Action("Index", "Recursos", new { requested = true })">Recursos</a></li>
                <li id="unitsAdmin"><a id="unitsURL" onclick="loadAdminView(this)" data-url="@Url.Action("Index", "Unidades", new { requested = true })">Unidades</a></li>
                <li id="usersAdmin"><a id="usersURL" onclick="loadAdminView(this)" data-url="@Url.Action("MenuUsuarios", "Usuarios", new { requested = true })">Usuarios</a></li>
                <li id="reportsAdmin"><a id="reportsURL" onclick="loadAdminView(this)" data-url="@Url.Action("FormularioReportes", "Home", new { requested = true })">Reportes</a></li>
            </ul>
        </section>
    </nav><br />

    <div>
        <loading></loading>
        <div id="managementTables">

        </div>
    </div>

<script src="~/Scripts/myScripts.js"></script>
<script type="text/javascript">
    $(document).ready(function () {

        debugger;

        if (sessionStorage.getItem('Tab') != undefined && sessionStorage.getItem('Tab') != "")
            loadAdminView("<a id='" + sessionStorage.getItem('Tab') + "' data-url='false'></a>");
        else
            loadAdminView("<a id='outreachURL' data-url='@Url.Action("MenuAlcance", "Alcance", new { requested = true })'></a>");
        
    });

</script>

OPDB/Views/Home/Buscar.cshtml
@model OPDB.Models.SearchViewModel

@{
    ViewBag.Title = "Resultados";
}

<h2>Resultados de Búsqueda</h2><br />
<div class="large-12 columns panel">
    <div class="large-6 columns">
       @if (Model.BuscarAlcance == true)
        {
            <h5><b>Entidades de Alcance</b></h5>
            <ul style="list-style-type: none;">
                @if (Model.OutreachEntities.Count() > 0)
                {
                    foreach (var outreach in Model.OutreachEntities)
                    {
                        <li>
                            @Html.ActionLink(outreach.OutreachEntityName, "Detalles", "Alcance", new { id = outreach.UserID }, new { @onclick = "sessionStorage.setItem('Route', 'home');" })
                        </li>
                    }
                }
                else
                {
                    <li>
                        No hubo resultados.
                    </li>
                }
            </ul>
            <br />
        }
        @if (Model.BuscarActividades == true)
        {
            <h5><b>Actividades</b></h5>
            <ul style="list-style-type: none;">
                @if (Model.Activities.Count() > 0)
                {
                    foreach (var activity in Model.Activities)
                    {
                        <li>
                            @Html.ActionLink(activity.Title, "Detalles", "Actividades", new { id = activity.ActivityID }, new { @onclick = "sessionStorage.setItem('Activity', 'home');" })
                        </li>
                    }
                }
                else
                {
                    <li>
                        No hubo resultados.
                    </li>
                }
            </ul>
            <br />
        }
        @if (Model.BuscarEscuelas == true)
        {
            <h5><b>Escuelas</b></h5>
            <ul style="list-style-type: none;">
                @if (Model.Schools.Count() > 0)
                {
                    foreach (var school in Model.Schools)
                    {
                        <li>
                            @Html.ActionLink(school.SchoolName, "Detalles", "Escuelas", new { id = school.SchoolID }, new { @onclick = "sessionStorage.setItem('Route', 'home');" })
                        </li>
                    }
                }
                else
                {
                    <li>
                        No hubo resultados.
                    </li>
                }
            </ul>
        }
        @if (Model.BuscarUnidades == true)
        {
            <h5><b>Unidades</b></h5>
            <ul style="list-style-type: none;">
                @if (Model.Units.Count() > 0)
                {
                    foreach (var unit in Model.Units)
                    {
                        <li>
                            <a href="#" title="Ver Detalles" class="modal_ajax_btn link" data-validation="false" data-title="@unit.UnitName" onclick="DisplayModal(this)" data-toggle="modal" data-url="@Url.Action("Detalles", "Unidades", new { id = unit.UnitID })">@unit.UnitName</a>
                        </li>
                    }
                }
                else
                {
                    <li>
                        No hubo resultados.
                    </li>
                }
            </ul>
            <br />
        }
        @if (Model.BuscarUsuarios == true)
        {
            <h5><b>Usuarios</b></h5>
            <ul style="list-style-type: none;">
                @if (Model.Users.Count() > 0)
                {
                    foreach (var user in Model.Users)
                    {
                        <li>
                            @Html.ActionLink(user.FirstName + " " + user.LastName, "Detalles", "Usuarios", new { id = user.UserID }, new { @onclick = "sessionStorage.setItem('Route', 'home');" })
                        </li>
                    }
                }
                else
                {
                    <li>
                        No hubo resultados.
                    </li>
                }
            </ul>
            <br />
        }

       
    </div>
    <div class="large-6 columns"><center><img src="@Url.Content("~/Images/search.svg")" height="297" width="297" style="margin-top:100px;"/></center></div>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        $("html").getNiceScroll().resize();

    });
</script>

OPDB/Views/Home/BusquedaAvanzada.cshtml
@{
    ViewBag.Title = "Búsqueda Avanzada";
    ViewBag.Nav = "Advanced";
}

<style>
    .side-nav{
        width: 200px;
        float: left;
    }

    footer{
        display: none !important;
    }
</style>
<h2>Búsqueda Avanzada</h2>
<span><b>Nota:</b> Debido a que la búsqueda es diacrítico-sensible puede requerir varios intentos. Intente varias permutaciones de sus parámetros.</span><br /><br />

<ul class="side-nav" style="border-right: 1px solid #dddddd;">
    <li id="alcance"><a onclick="getAdvancedSearchForm(this)" data-url="@Url.Action("_PartialViewLoad", "Home", new { view = "_Alcance" })">Alcance</a></li>
    <li id="actividades"><a onclick="getAdvancedSearchForm(this)" data-url="@Url.Action("_PartialViewLoad", "Home", new { view = "_Actividades" })">Actividades</a></li>
    <li id="escuelas"><a onclick="getAdvancedSearchForm(this)" data-url="@Url.Action("_PartialViewLoad", "Home", new { view = "_Escuelas" })">Escuelas</a></li>
    <li id="unidades"><a onclick="getAdvancedSearchForm(this)" data-url="@Url.Action("_PartialViewLoad", "Home", new { view = "_Unidades" })">Unidades</a></li>
    <li id="usuarios"><a onclick="getAdvancedSearchForm(this)" data-url="@Url.Action("_PartialViewLoad", "Home", new { view = "_Usuarios" })">Usuarios</a></li>
</ul>

<div id="searchForm" style="float: left; margin-left: 5%;">


</div>

<script src="~/Scripts/myScripts.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        getAdvancedSearchForm("<a data-url='@Url.Action("_PartialViewLoad", "Home", new { view = "_Alcance" })'></a>");

    });
</script>

OPDB/Views/Home/Calendario.cshtml
@model OPDB.Models.ActivityViewModel


@{
    ViewBag.Title = "Calendario";
    ViewBag.Nav = "Calendario";
}

<div style="">
    <div id="calendario"></div>
</div>

<script src="~/Scripts/moment/moment.js"></script>
<script src="~/Scripts/fullcalendar/fullcalendar.min.js"></script>
<script src="~/Scripts/fullcalendar/es.js"></script>

<script type="text/javascript">

    $(document).ready(function () {
        
        sessionStorage.setItem('Activity', 'calendar');

        $('#calendario').fullCalendar({
            theme: false,
            aspectRatio: 2,
            firstDay: 0,
            contentHeight: "auto",
            lang: "es",
            events: "@Url.Action("CalendarData", "Home")",
            timeFormat: 'h:mmT'
        });

    });

</script>

OPDB/Views/Home/Index.cshtml
@model OPDB.Models.HomeViewModel

@{
    ViewBag.Title = "Inicio";
}

<style>
    span {
        font-size: 0.875rem;
        color: #4d4d4d;
    }

    r {
        font-size: 0.875rem;
    }

    .link:hover {
        color: #007A0B !important;
    }
</style>

<h3>Próximas Actividades</h3><br />
@if (Model.Information.Count > 0)
{
    foreach (var item in Model.Information)
    {

        <div class="large-6 columns panel" style="height:250px;">
            <h4>@Html.ActionLink(item.Activity.Title, "Detalles", "Actividades", new { id = item.Activity.ActivityID }, new { @style = "color:black;", @class = "link", @onclick = "sessionStorage.setItem('Activity', 'home');" })</h4>
                <div class="activity" style="height:150px; overflow:hidden;" title="Desplace hacia abajo para más información">                
                <span>Propósito: </span><r>@String.Concat(item.Activity.Purpose.Substring(0, item.Activity.Purpose.Length > 100 ? 100 : item.Activity.Purpose.Length), "")</r><br />
                <span>Tipo: </span><r>@item.Activity.ActivityType.ActivityType1</r><br />
                <span>Área de Especialidad: </span><r>@item.Activity.ActivityMajor.ActivityMajor1</r><br />
                @if (item.ActivityDynamic.ActivityDynamic1 != null && item.ActivityDynamic.ActivityDynamic1 != "")
                {<span>Dinámica de la Actividad: </span><r>@item.ActivityDynamic.ActivityDynamic1</r><br />}
                <span>Audiencia: </span><r>@item.Activity.TargetPopulation.TargetPopulation1</r><br />
                @if (item.Activity.Location != null && item.Activity.Location != "")
                {<span>Localización: </span><r>@item.Activity.Location</r><br /> }
                @if (item.Activity.ActivityDate != null && item.Activity.ActivityDate != new DateTime())
                { <span>Fecha: </span><r>@item.Activity.ActivityDate.Value.ToString("dd/MM/yyyy")</r><br />}
                @if (item.Activity.ActivityTime != null && item.Activity.ActivityTime != "")
                { <span>Hora: </span><r>@item.Activity.ActivityTime</r><br />}
                @if (item.EndDate != new DateTime())
                {
                    if (item.Activity.Duration.Split('/')[1] == "Minutes" || item.Activity.Duration.Split('/')[1] == "Hours")
                    {<span>Finaliza: </span><r>@item.EndDate.ToString("hh:mm tt")</r><br />

                    }
                    else
                    {<span>Finaliza: </span><r>@item.EndDate.ToString("dd/MM/yyyy hh:mm tt")</r><br />}

                }
            </div>

            @if (Request.IsAuthenticated)
            {
                if (Int32.Parse(User.Identity.Name.Split(',')[1]) != 3)
                {
                    if (item.Interested != true)
                    {
                        <a style="float:right;" class="btn btn-sm" onclick="showInterest(this)" data-url="@Url.Action("Interes", "Actividades", new { id = item.Activity.ActivityID })" title="Mostrar Interes"><i class="fa fa-thumbs-up"></i> Me Interesa</a>
                    }
                    else
                    {
                        <i style="float:right; font-size:0.875rem;">Te interesa esta actividad.</i>
                    }
                }
            }
        </div>


    }
}
else
{
    <div class="large-12 columns panel" style="height:250px;">
        No hay ninguna actividad esta semana.
    </div>
}
<br />

<script src="~/Scripts/myScripts.js"></script>
<script>
    $(document).ready(function () {

        $(".activity").niceScroll();
    });
</script>

OPDB/Views/Home/ResultadosReporte.cshtml
@model OPDB.Models.ReportViewModel

@{
    ViewBag.Title = "Resultados Reporte";
}

<h2>Resultados Reporte</h2>

<div class="large-12 columns panel callout">
    <ul style="list-style-type: none;">
        @if (Model.Results.Count() > 0)
        {
            foreach (var result in Model.Results)
            {

                <li>
                    @Html.ActionLink(result.Title, "Detalles", "Actividades", new { id = result.ActivityID }, null)
                </li>
            }
        }
        else
        {
            <li>
                No hubo resultados.
            </li>
        }

    </ul>
</div>