OPDB/Controllers/RecursosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OPDB.Models;

namespace OPDB.Controllers
{
    public class RecursosController : Controller
    {
        /// <summary>
        /// A private instance of the OPDB Database model.
        /// </summary>
        private OPDBEntities db = new OPDBEntities();


        /// <summary>
        /// The resource index, returns the system admin view.
        /// </summary>
        /// <returns>The system admin view for resources.</returns>
        public ActionResult Index(string requested)
        {

            if (requested != null)
            {
                if (User.Identity.IsAuthenticated)
                {
                    if (Int32.Parse(User.Identity.Name.Split(',')[1]) == 1)
                    {
                        List<Resource> resources = (from resource in db.Resources where resource.DeletionDate == null select resource).ToList();

                        ResourceViewModel resourceViewModel = new ResourceViewModel
                        {
                            Information = new List<UserInfoViewModel>()
                        };


                        foreach (var resource in resources)
                        {
                            resourceViewModel.Information.Add(new UserInfoViewModel
                            {
                                Resource = resource,
                                CreateUser = db.UserDetails.First(r => r.UserID == resource.CreateUser),
                                UpdateUser = db.UserDetails.First(r => r.UserID == resource.UpdateUser)

                            });
                        }

                        return PartialView("Index", resourceViewModel);
                    }
                }
            }

            return RedirectToAction("AccesoDenegado", "Home");
        }

        /// <summary>
        /// Displays the resource detail page.
        /// </summary>
        /// <param name="id">The id of the resource to retrieve from the database.</param>
        /// <returns>The specified resource's details page.</returns>
        [HttpPost]
        public ActionResult Detalles(int id = 0)
        {
            if (User.Identity.IsAuthenticated)
            {
                if (Int32.Parse(User.Identity.Name.Split(',')[1]) == 1)
                {
                    Resource resource = db.Resources.Find(id);

                    ResourceViewModel resourceViewModel = new ResourceViewModel
                    {
                        Resource = resource,
                        Unit = db.Units.Find(resource.UnitID),
                        Units = getUnits()
                    };

                    if (resourceViewModel.Resource == null)
                    {
                        return HttpNotFound();
                    }

                    return PartialView("Detalles", resourceViewModel);
                }
            }

            return RedirectToAction("AccesoDenegado", "Home");
        }


        /// <summary>
        /// Create resource view.
        /// </summary>
        /// <returns>The create new resource view.</returns>
        [HttpPost]
        public ActionResult PopUpCrear()
        {
            if (User.Identity.IsAuthenticated)
            {
                if (Int32.Parse(User.Identity.Name.Split(',')[1]) == 1)
                {
                    ResourceViewModel resourceViewModel = new ResourceViewModel
                    {
                        Units = getUnits()
                    };
                    return PartialView("Crear", resourceViewModel);
                }
            }

            return RedirectToAction("AccesoDenegado", "Home");
        }


        /// <summary>
        /// Create a new resource.
        /// </summary>
        /// <param name="resourceViewModel">The ResourceViewModel containing the information of the resource to be created.</param>
        /// <returns>The resource admin view if successful, the create new resource view if an error occurs.</returns>
        [HttpPost]
        public ActionResult Crear(ResourceViewModel resourceViewModel)
        {
            if (User.Identity.IsAuthenticated)
            {
                if (Int32.Parse(User.Identity.Name.Split(',')[1]) == 1)
                {
                    int userID = Int32.Parse(User.Identity.Name.Split(',')[0]);

                    try
                    {
                        if (ModelState.IsValid)
                        {
                            resourceViewModel.Resource.CreateDate = DateTime.Now;
                            resourceViewModel.Resource.UpdateDate = DateTime.Now;

                            // Change after login implementation.
                            resourceViewModel.Resource.CreateUser = userID;
                            resourceViewModel.Resource.UpdateUser = userID;

                            db.Resources.Add(resourceViewModel.Resource);
                            db.SaveChanges();

                           return View("_Hack");
                        }

                        return Content(GetErrorsFromModelState(resourceViewModel));
                    }

                    catch (Exception)
                    {
                        return Content(GetErrorsFromModelState(resourceViewModel));
                    }
                }
            }

            return RedirectToAction("AccesoDenegado", "Home");

        }


        /// <summary>
        /// Edit resource view.
        /// </summary>
        /// <param name="id">The id of the resource to be edited.</param>
        /// <returns>The edit view with the specified resource.</returns>
        [HttpPost]
        public ActionResult PopUpEditar(int id = 0)
        {
            if (User.Identity.IsAuthenticated)
            {
                if (Int32.Parse(User.Identity.Name.Split(',')[1]) == 1)
                {

                    ResourceViewModel resourceViewModel = new ResourceViewModel
                    {
                        Resource = db.Resources.Find(id),
                        Units = getUnits()

                    };

                    if (resourceViewModel.Resource == null)
                    {
                        return HttpNotFound();
                    }


                    return PartialView("Editar", resourceViewModel);
                }
            }

            return RedirectToAction("AccesoDenegado", "Home");
        }


        /// <summary>
        /// Edit a resource.
        /// </summary>
        /// <param name="resourceViewModel">The ResourceViewModel containing the edited resource parameters.</param>
        /// <returns>The admin resource page if successful, the edit resource view if an error occurs.</returns>
        [HttpPost]
        public ActionResult Editar(ResourceViewModel resourceViewModel)
        {
            if (User.Identity.IsAuthenticated)
            {
                if (Int32.Parse(User.Identity.Name.Split(',')[1]) == 1)
                {
                    int userID = Int32.Parse(User.Identity.Name.Split(',')[0]);

                    if (ModelState.IsValid)
                    {
                        //To be changed with login.
                        resourceViewModel.Resource.UpdateUser = userID;

                        resourceViewModel.Resource.UpdateDate = DateTime.Now;
                        db.Entry(resourceViewModel.Resource).State = EntityState.Modified;
                        db.SaveChanges();

                        return View("_Hack");
                    }

                    return Content(GetErrorsFromModelState(resourceViewModel));
                }
            }

            return RedirectToAction("AccesoDenegado", "Home");
        }

        /// <summary>
        /// Remove a resource from the system.
        /// </summary>
        /// <param name="id">The id of the resource to be removed.</param>
        /// <returns>The admin resource page if successful, a "Resource Not Found" page if an error occurs.</returns>
        [HttpPost]
        public ActionResult Remover(int id = 0)
        {
            if (User.Identity.IsAuthenticated)
            {
                if (Int32.Parse(User.Identity.Name.Split(',')[1]) == 1)
                {
                    Resource resource = db.Resources.Find(id);
                    if (resource == null)
                    {
                        return HttpNotFound();
                    }
                    else
                    {
                        resource.DeletionDate = DateTime.Now;
                        db.Entry(resource).State = EntityState.Modified;
                        db.SaveChanges();
                    }

                    return RedirectToAction("Administracion", "Home");
                }
            }

            return RedirectToAction("AccesoDenegado", "Home");
        }

        /// <summary>
        /// Retrieve all available Units from the database.
        /// </summary>
        /// <returns>A list containing select list items representing the system Units.</returns>
        public List<SelectListItem> getUnits()
        {
            List<SelectListItem> types = new List<SelectListItem>();
            foreach (var unit in db.Units)
            {

                types.Add(new SelectListItem()
                {
                    Text = unit.UnitName,
                    Value = unit.UnitID + ""

                });

            }

            return types;
        }

        public String GetErrorsFromModelState(ResourceViewModel resourceViewModel)
        {

            //retrieves the validation messages from the ModelState as strings    
            var str = "";
            var errorSates = from state in ModelState.Values
                             from error in state.Errors
                             select error.ErrorMessage;

OPDB/Views/Recursos/Crear.cshtml
@model OPDB.Models.ResourceViewModel

@{
    ViewBag.Title = "Create";
    var formAttributes = new Dictionary<string, object>();
    formAttributes.Add("novalidate", "novalidate");
}

@using (Ajax.BeginForm("Crear", "Recursos", new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "validation" }))
{
    @Html.ValidationSummary(false)
    
            <div class="editor-label">
              @Html.LabelFor(model => model.Resource.Resource1, "Recurso *")
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Resource.Resource1)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.Resource.UnitID, "Unidad *")
            </div>
            <div class="editor-field">
                @Html.DropDownListFor(model => model.Resource.UnitID, Model.Units, new { @style = "margin: 0 0 1rem 0 !important; padding: 0.5rem !important; height: 2.55rem !important; width: 100% !important;" })
             </div>

            <input type="submit" class="btn" style="float:left !important; width:40% !important; margin-left: 30px !important;" value="Crear" />    <input type="button" class="btn" style="float:right !important; width:40% !important; margin-bottom: 20px !important; margin-right: 30px !important;" value="Cancelar" onclick="modalClose()" />

}

        @section Scripts {
            @Scripts.Render("~/bundles/jqueryval")
        }

OPDB/Views/Recursos/Detalles.cshtml
@model OPDB.Models.ResourceViewModel

@{
    ViewBag.Title = "Detalles";
}
<style>
    span {
        font-size: 0.875rem;
        color: #4d4d4d;
    }
</style>
    <div>
        @Html.LabelFor(model => model.Unit.UnitName, "Unidad")
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Unit.UnitName)
    </div>
    <div>
        @Html.LabelFor(model => model.Unit.RoomNumber, "Oficina o Salón")
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Unit.RoomNumber)
    </div>
    <div>
        @Html.LabelFor(model => model.Unit.PhoneNumber, "Teléfono")
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Unit.PhoneNumber)
    </div><br />
<a href="#" title="Editar" class="modal_ajax_btn" data-title="Editar Recurso" onclick="DisplayModal(this)" data-toggle="modal" data-url="@Url.Action("PopUpEditar", "Recursos", new { id = Model.Resource.ResourceID })"><input type="button" class="btn" style="float:left !important; width:40% !important; margin-left: 30px !important;" value="Editar" /></a>
<input type="button" class="btn" style="float:right !important; width:40% !important; margin-bottom: 20px !important; margin-right: 30px !important;" value="Volver" onclick="modalClose()" />

OPDB/Views/Recursos/Editar.cshtml
@model OPDB.Models.ResourceViewModel


@using (Ajax.BeginForm("Editar", "Recursos", new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "validation" }))
    {
        @Html.ValidationSummary(false)
            @Html.HiddenFor(model => model.Resource.ResourceID)
            @Html.HiddenFor(model => model.Resource.CreateUser)
            @Html.HiddenFor(model => model.Resource.CreateDate)

            <div class="editor-label">
                @Html.LabelFor(model => model.Resource.Resource1, "Recurso *")
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Resource.Resource1)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.Resource.UnitID, "Unidad *")
            </div>
            <div class="editor-field">
                @Html.DropDownListFor(model => model.Resource.UnitID, Model.Units, new { @style = "margin: 0 0 1rem 0 !important; padding: 0.5rem !important; height: 2.55rem !important; width: 100% !important;" })
            </div>
            <br />
            <p>
                <input type="submit" class="btn" style="float:left !important; width:40% !important; margin-left: 30px !important;" value="Guardar" /> <input type="button" class="btn" value="Cancelar" style="float:right !important; width:40% !important; margin-bottom: 20px !important; margin-right: 30px !important;" onclick="modalClose()" />
            </p>
    }
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

OPDB/Views/Recursos/Index.cshtml
@model OPDB.Models.ResourceViewModel
@using Microsoft.Ajax.Utilities

@{
    ViewBag.Title = "Recursos";
}

<style>
    select {
        width: 50px !important;
        padding: 0.2rem !important;
        height: 1.6rem !important;
        margin: 0 !important;
    }

    label {
        width: 100% !important;
    }

    input[type="search"] {
        padding: 0.2rem;
    }

    th, td {
        text-align: center !important;
    }

    .previous, .next{
        display: none !important;
    }

    i{
        cursor: pointer;
    }

     a:not(.button) {
      color: black; }

        a span i:hover {
        color: #007A0B;
    }

    .link:hover {
        color: #007A0B !important;
    }

    .fa-remove:hover {
        color: #007A0B !important;
    }
</style>
<div>
    <table id="resources">
        <thead>
            <tr>
                <th>Recurso</th>
                <th>Creado Por</th>
                <th>En</th>
                <th>Modificado Por</th>
                <th>En</th>
                <th style="width:6%"></th>
            </tr>
        </thead>

        <tbody>
            @foreach (var item in Model.Information)
            {
                <tr>
                    <td>
                        <a href="#" title="Ver Detalles" class="modal_ajax_btn link" data-validation="false" data-title="@item.Resource.Resource1" onclick="DisplayModal(this)" data-toggle="modal" data-url="@Url.Action("Detalles", "Recursos", new { id = item.Resource.ResourceID })">@item.Resource.Resource1</a>
                     </td>
                    <td>
                        @Html.ActionLink(item.CreateUser.FirstName + " " + item.CreateUser.MiddleInitial + " " + item.CreateUser.LastName, "Detalles", "Usuarios", new { id = item.Resource.CreateUser }, new { @class = "link", @onclick = "sessionStorage.setItem('Route', 'admin');" })
                    <td>
                        @Html.DisplayFor(modelItem => item.Resource.CreateDate)
                    </td>
                    <td>
                       @Html.ActionLink(item.UpdateUser.FirstName + " " + item.UpdateUser.MiddleInitial + " " + item.UpdateUser.LastName, "Detalles", "Usuarios", new { id = item.Resource.UpdateUser }, new { @class = "link", @onclick = "sessionStorage.setItem('Route', 'admin');" })
                     </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Resource.UpdateDate)
                    </td>
                    <td>
                        <a href="#" title="Editar" data-title="Editar Recurso" onclick="DisplayModal(this)" data-toggle="modal" data-url="@Url.Action("PopUpEditar", "Recursos", new { id = item.Resource.ResourceID })" class="modal_ajax_btn link"><i class="fa fa-pencil"></i></a> 
                        <i title="Remover" style="cursor:pointer;" class="fa fa-remove" onclick="removeRecord(this, 'resources')" data-url="@Url.Action("Remover", "Recursos", new { id = item.Resource.ResourceID })"></i>
                    </td>
                </tr>
            }
        </tbody>

    </table>
    <br />
    <a href="#" title="Crear Recurso" class="modal_ajax_btn" data-title="Nuevo Recurso" onclick="DisplayModal(this)" data-toggle="modal" data-url="@Url.Action("PopUpCrear", "Recursos", null)"><input type="button" class="btn" value="Nuevo Recurso"/></a>
   
</div><br />

<script src="~/Scripts/myScripts.js"></script>
<script>
    $(document).ready(function () {

        sessionStorage.setItem('Tab', 'resourcesURL');

        $('#resources').DataTable({
            "sDom": '<"top"f>t<"bottom"ipr><"clear">',
            "sPaginationType": "full_numbers",
            "bProcessing": false,
            "iDisplayLength": 10,
            "aaSorting": [[1, "asc"]],
            "columnDefs": [
                {
                    "orderable": false,
                    "targets": 5
                }


            ],
            "oLanguage": {
                "sEmptyTable": "No se ha añadido ningún recurso",
                "sZeroRecords": "No se ha encontrado ningún registro",
                "sSearch": "Buscar:"
            }
        });

        document.getElementsByTagName("loading")[0].innerHTML = "";
    });

</script>